server:
  port: 8080
#  servlet:
#    context-path: ./
spring:
  datasource:
    one:
      # url: jdbc:mysql://localhost:3306/light?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      url: jdbc:mysql://10.62.252.166:6303/light?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: lego_dev
      password: lego798
  #    driver-class-name: com.mysql.jdbc.Drivers
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  thymeleaf:
    encoding: UTF-8
    content-type: text/html
    mode: html5
    cache: false
    prefix: classpath:/templates/
    suffix: .html